version: "3.7"
services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth_server
      - resource_server
    volumes:
      - ./client/index.html:/usr/share/nginx/html/index.html
  auth_server:
    build:
      context: ./auth_server
      dockerfile: ./Dockerfile
    volumes:
      - ./auth_server:/usr/src/app
  resource_server:
    build:
      context: ./resource_server
      dockerfile: ./Dockerfile
    volumes:
      - ./resource_server:/usr/src/app
